# Generated by Django 2.2 on 2019-06-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(default='none', upload_to='profile/picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='url',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
