# Generated by Django 2.2 on 2019-06-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190620_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='photo',
            new_name='image',
        ),
    ]
