# Generated by Django 2.2.2 on 2019-08-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_aboutme_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
