# Generated by Django 2.2.4 on 2019-08-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_author_name', models.CharField(max_length=100)),
                ('reservation_author_email', models.EmailField(max_length=254)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='blog.Offer')),
            ],
        ),
    ]
