# Generated by Django 2.2.4 on 2019-08-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
