# Generated by Django 2.2.4 on 2019-09-14 19:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_homedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Messages', max_length=50)),
                ('reservationMessage', ckeditor_uploader.fields.RichTextUploadingField()),
                ('contactMessage', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
