export const SET_PICTURES = 'SET_PICTURES';
export const FETCH_PICTURES_FAILED = 'FETCH_PICTURES_FAILED';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const SET_ARTICLES = 'SET_ARTICLES';
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED';

export const SET_OFFERS = 'SET_OFFERS';
export const FETCH_OFFERS_FAILED = 'FETCH_OFFERS_FAILED';

export const TOGGLE_NAV = 'TOGGLE_NAV';