# Generated by Django 2.2.4 on 2019-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0003_auto_20190822_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Article tags', max_length=255),
        ),
    ]
