# Generated by Django 2.2.4 on 2019-08-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0004_article_meta_keywords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
