# Generated by Django 2.2.4 on 2019-08-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0006_newsletterusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUsers',
            new_name='NewsletterUser',
        ),
    ]
