# Generated by Django 2.2.4 on 2019-09-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0010_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
