# Generated by Django 2.2.4 on 2019-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0011_delete_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('wallpaper', models.ImageField(upload_to='blog_theme/pictures')),
            ],
        ),
    ]
