# Generated by Django 2.2.4 on 2019-09-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/picture/'),
        ),
    ]
